services:
  app:
    image: analytics-api:v1
    build: 
      context: .
      dockerfile: Dockerfile.web
    environment:
      - PORT=8002
    env_file:
      - .env
    ports:
      - "8002:8002"
    command: uvicorn main:app --host 0.0.0.0 --port 8002 --reload
    volumes:
      - ./src:/code:rw
    depends_on:
      - db

  db:
    image: timescale/timescaledb:latest-pg16
    environment:
      POSTGRES_USER: timescale_user
      POSTGRES_PASSWORD: timePW
      POSTGRES_DB: timescale_db
    ports:
      - "5432:5432"
    volumes:
      - timescale_data:/var/lib/postgresql/data

volumes:
  timescale_data: